import test from 'node:test';import assert from 'node:assert/strict';import {marketEntries,selectedQuote,listingState,productFoldKey} from '../lib/market-view.mjs';
import {openDb,storeSnapshot} from '../lib/db.mjs';import {createApp} from '../lib/web.mjs';
test('公开HTML隐藏实现来源，旧详情canonical保留，官方/API零价不误删',async()=>{const db=openDb(':memory:');for(const source of ['direct-shops','priceai','ldxp-goods','cardnav-official','goaihop-relay'])storeSnapshot(db,{source,snapshotId:'fixture',fetchedAt:'2026-09-05T00:00:00Z',stale:source==='goaihop-relay',products:[{productId:'claude-pro-month',name:source==='ldxp-goods'?'LDXP 搜索「Claude」':'Claude Pro',platform:'Claude',productType:'订阅/会员',spec:source==='direct-shops'?'原始店铺直采':'Pro',currency:'CNY',lowestPrice:0,offers:[{offerId:'offer',title:'Claude Pro 1个月 独享',storeName:'测试店',price:['cardnav-official','goaihop-relay'].includes(source)?0:100,status:'online',url:'https://16688.com.cn/goods/1',stockCount:1}]}]});const app=createApp({db});await new Promise(r=>app.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.address().port;try{for(const channel of ['all','16688']){const home=await(await fetch(base+'/?channel='+channel)).text();if(channel==='all'){assert.match(home,/官方订阅参考/);assert.match(home,/API 服务套餐/);assert.match(home,/>¥0</);}else{assert.doesNotMatch(home,/API 服务套餐/);}assert.match(home,/Kami|Dujiao/);const visible=home.replace(/<script[\s\S]*?<\/script>/g,'').replace(/<style[\s\S]*?<\/style>/g,'').replace(/<[^>]+>/g,'');assert.doesNotMatch(visible,/PriceAI|原店直采|原始店铺直采|Top\s*5|CardNav|GoAIHop|LDXP/);}const detail=await(await fetch(base+'/product?source=direct-shops&id=claude-pro-month')).text();assert.match(detail,/rel="canonical" href="https:\/\/airadar.vip\/product\?source=direct-shops&amp;id=claude-pro-month"/);assert.doesNotMatch(detail.match(/<head>[\s\S]*?<\/head>/)[0],/原始店铺直采|PriceAI|LDXP/);const api=await(await fetch(base+'/product?source=goaihop-relay&id=claude-pro-month&channel=16688')).text();assert.match(api,/price-display">¥0</);assert.doesNotMatch(api,/>服务在线</);assert.equal((await fetch(base+'/product?source=direct-shops&id=missing')).status,404);}finally{await new Promise(r=>app.close(r));db.close()}});
const offer=(price,status='in_stock',store='同一店')=>({price,status,stock_count:status==='unknown'?null:2,store_name:store,url:'https://16688.com.cn/goods/1'});
test('非商店缺价不被Number(null)伪造免费价',async()=>{const db=openDb(':memory:');storeSnapshot(db,{source:'goaihop-relay',snapshotId:'missing',fetchedAt:'2026-09-05T00:00:00Z',products:[{productId:'missing-price',name:'缺价方案',platform:'API',currency:'CNY',lowestPrice:null,offers:[{offerId:'missing',price:null,url:'https://16688.com.cn/goods/1',status:'online'}]}]});const app=createApp({db});await new Promise(r=>app.listen(0,'127.0.0.1',r));try{const html=await(await fetch('http://127.0.0.1:'+app.address().port+'/?channel=16688')).text();assert.doesNotMatch(html,/>¥0</);assert.match(html,/当前筛选下暂无匹配报价/);}finally{await new Promise(r=>app.close(r));db.close()}});
const list=(source,price,patch={})=>({source,stale:false,products:[{product_id:'claude-pro-month',name:'Claude Pro',product_type:'订阅/会员',currency:'CNY',spec:source==='direct-shops'?'原始店铺直采':'Pro',selected_offer:offer(price),...patch}]});
test('期限即使同时出现在name和spec也不能作为冗余消掉',()=>{const annual=list('direct-shops',100,{name:'Claude Pro 12个月',spec:'12个月'});assert.equal(marketEntries([annual,list('priceai',100,{name:'Claude Pro 1个月',spec:'1个月'})]).length,2);assert.equal(marketEntries([annual,list('priceai',100,{spec:null})]).length,2)});
test('展示候选的价格店名平台来自同一可售报价，低价unknown不冒充在售',()=>{const selected=selectedQuote([offer(1,'unknown','未核实店'),offer(100,'in_stock','在售店')]);assert.equal(selected.price,100);assert.equal(selected.store_name,'在售店');assert.equal(listingState(offer(1,'unknown')),'待确认');assert.equal(listingState(selected,true),'待核验');assert.equal(listingState(offer(100,'low_stock')),'库存紧张')});
test('目录折叠保守匹配，同价优先独立且不相加数量，陈旧候选不抢鲜活可售价',()=>{const a=list('direct-shops',100),b=list('priceai',100);let result=marketEntries([b,a]);assert.equal(result.length,1);assert.equal(result[0].list.source,'direct-shops');assert.equal(result[0].alternatives.length,1);assert.equal(result[0].channel.id,'16688');a.stale=true;a.products[0].selected_offer=offer(1);result=marketEntries([a,b]);assert.equal(result[0].offer.price,100);assert.equal(marketEntries([list('direct-shops',100,{spec:'12个月'}),b]).length,2);assert.equal(marketEntries([list('direct-shops',100,{currency:'USD'}),b]).length,2);assert.notEqual(productFoldKey({source:'direct-shops'},{product_id:'chatgpt-plus'}),productFoldKey({source:'priceai'},{product_id:'chatgpt-plus'}));assert.equal(marketEntries([a,list('ldxp-goods',50)]).length,2)});
