// Small shared styles for the category -> product -> specification flow.
export const DIRECTORY_CSS = `
  .product-nav{overflow:visible}.product-nav-inner{overflow:visible;flex-wrap:wrap;justify-content:flex-start;gap:6px;padding-top:8px;padding-bottom:8px}.product-filter{flex:none;min-height:36px;padding:7px 10px}.category-more{position:relative;align-self:center}.category-more>summary{padding:8px 12px;cursor:pointer;white-space:nowrap;color:var(--muted);font-size:13px}.category-more-menu{position:absolute;z-index:40;top:calc(100% + 5px);right:0;min-width:170px;padding:6px;background:var(--surface);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow)}.category-more-menu .product-filter{display:flex}.directory-more{margin-top:20px}.directory-more>summary{width:max-content;padding:8px 0;cursor:pointer;color:var(--muted);font-size:13px}.directory-more .directory-list{margin-top:8px}
  .directory{max-width:920px;margin:0 auto 32px}.directory-intro{padding:12px 0 24px}.directory-intro h1{margin:0;font-size:30px;letter-spacing:-.035em}.directory-intro p{margin:8px 0 0;color:var(--muted);font-size:13px}.directory-list{border-top:1px solid var(--line)}.directory-row{display:flex;align-items:center;justify-content:space-between;gap:24px;min-height:78px;padding:19px 4px;border-bottom:1px solid var(--line);color:var(--text)}a.directory-row:hover{background:var(--soft);color:var(--text)}.directory-row h2{margin:0;font-size:17px;font-weight:650;line-height:1.5}.directory-action{display:inline-flex;align-items:center;gap:8px;flex-shrink:0;font-size:13px;color:var(--blue)}.directory-variant{display:grid;grid-template-columns:minmax(0,1fr) auto auto}.directory-variant h2{font-size:15px}.directory-variant p{margin:6px 0 0;color:var(--muted);font-size:12px}.directory-variant .money{font-size:20px}.directory-empty{padding:30px 0;color:var(--muted);font-size:14px}.detail-filters{margin:0 0 18px}.detail-filters>summary{width:max-content;cursor:pointer;font-size:13px;color:var(--muted)}.detail-filters .channel-form{margin-top:12px}.spec-selector{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin:0 0 20px}.spec-selector-label{margin-right:4px;color:var(--muted);font-size:13px}.spec-choice{padding:8px 12px;border:1px solid var(--line);border-radius:6px;font-size:13px}.spec-choice[aria-current="true"]{border-color:var(--blue);background:var(--blue-soft);color:var(--blue-deep)}
  .product-filter{min-height:44px;font-size:14px}.category-more>summary{min-height:44px;padding:11px 12px;font-size:14px}.directory-action{min-height:44px;padding:8px 4px}.spec-choice{display:inline-flex;align-items:center;min-height:44px}.detail-filters>summary,.directory-more>summary{min-height:44px;padding-top:11px;padding-bottom:11px}
  .category-more.active>summary{color:var(--blue);font-weight:650}
  @media(min-width:761px){.product-nav-inner{justify-content:center}}
  @media(max-width:600px){.directory-intro{padding:4px 0 20px}.directory-intro h1{font-size:25px}.directory-row{min-height:72px;gap:16px}.directory-variant{grid-template-columns:minmax(0,1fr) auto}.directory-variant .directory-action{grid-column:1/-1;justify-self:end}.directory-row h2{font-size:16px}.product-nav-inner{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px}.product-nav-inner>.product-filter{justify-content:center;min-width:0;padding:4px;gap:4px;font-size:13px}.product-nav-inner>.product-filter[data-family-filter="relay"] .product-filter-mark,.product-nav-inner>.product-filter[data-family-filter="mail"] .product-filter-mark{display:none}.product-nav-inner>.category-more{width:100%;min-width:0}.product-nav-inner>.category-more>summary{min-height:44px;padding:11px 4px;text-align:center;font-size:13px}.category-more-menu{right:0}.spec-choice{max-width:100%;overflow-wrap:anywhere}}
  @media(max-width:360px){.product-nav-inner>.product-filter,.product-nav-inner>.category-more>summary{font-size:12px}.product-nav-inner>.product-filter .product-filter-mark{display:none}}
`;
