import {merchantStyles} from './merchant-ui.mjs';
import {shopDescriptorForOffer} from './merchant-x.mjs';
import {safeExternalLink} from './admin-links.mjs';
import {outboundHref} from './outbound.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={draft:'等待提交核验资料',pending:'等待人工审核',approved:'X 关联已展示',rejected:'本次未通过',revoked:'X 关联已撤销'};
const shopPath=id=>'/shop?'+new URLSearchParams({id});
export const xShareHref=(text,url)=>'https://twitter.com/intent/tweet?'+new URLSearchParams({text,url});
export const MERCHANT_X_CSS=`
.merchant-x,.offer-title .merchant-x,.merchant .merchant-x{box-sizing:border-box;display:inline-flex;align-items:center;gap:7px;max-width:100%;vertical-align:middle;margin:3px 0 3px 7px;padding:5px 9px 5px 5px;border:1px solid #b8d7f7;border-radius:10px;color:#174a78;background:#edf6ff;box-shadow:0 1px 2px #123c6510;font:650 12px/1.4 system-ui,sans-serif;letter-spacing:0;text-decoration:none;white-space:nowrap;transition:background-color .15s,border-color .15s,box-shadow .15s}
.merchant-x:hover,.merchant .merchant-x:hover{color:#103d68;background:#deeeff;border-color:#7db5ee;box-shadow:0 2px 6px #123c651a;text-decoration:none}
.merchant-x:focus-visible{outline:2px solid #1673c9;outline-offset:3px}
.merchant-x .merchant-x-logo{box-sizing:border-box;display:inline-flex;align-items:center;justify-content:center;flex:0 0 22px;width:22px;height:22px;border-radius:6px;background:#111820;color:#fff}
.merchant-x-logo svg{display:block;width:12px;height:12px;fill:currentColor}
.merchant-x .merchant-x-handle{min-width:0;overflow:hidden;text-overflow:ellipsis;color:inherit;font:inherit;line-height:1.4}
.merchant-x .merchant-x-check{display:block;flex:0 0 15px;width:15px;height:15px;color:#187bd1}
.merchant .x-public-account .merchant-x{max-width:100%}
@media(prefers-reduced-motion:reduce){.merchant-x{transition:none}}
.merchant-store-links{display:flex;gap:12px;flex-wrap:wrap;margin-top:6px;font-size:12px;color:#687b70}.merchant-store-links a{color:#536f60}.merchant .x-claim-code{font:700 24px ui-monospace,monospace;letter-spacing:.04em;background:#eff5f1;border-radius:8px;padding:14px;display:block;margin:14px 0}.merchant .x-proof-text{width:100%;min-height:150px}.merchant .x-actions{display:flex;gap:10px;flex-wrap:wrap}.merchant .x-actions a,.merchant a.x-button{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:9px 14px;border:1px solid #cad8cf;border-radius:8px;background:white;text-decoration:none;font-size:14px}.merchant .x-actions a.primary{background:#28634b;color:#fff;border-color:#28634b}.merchant .x-steps{display:flex;gap:12px;flex-wrap:wrap;color:#6a7c71;font-size:13px}.merchant .x-list-row{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #e1e9e3;padding:20px 0}.merchant .x-list-row h2{margin-bottom:7px}.merchant .x-list-row p{margin:7px 0}.merchant .x-list-row .money{font-size:23px;white-space:nowrap}.merchant .x-list-buy{display:flex;flex-direction:column;gap:8px;align-items:flex-end}.merchant [hidden]{display:none!important}.merchant .x-proof-options{margin:20px 0}.merchant .x-note{font-size:13px;color:#65796c}.merchant .x-public-account{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:20px 0}.merchant .x-public-account .merchant-x{font-size:17px;padding:8px 12px;margin:0}@media(max-width:600px){.merchant .x-list-row{display:block}.merchant .x-list-buy{align-items:flex-start;margin-top:12px}.merchant .x-actions a{flex:1}.merchant .x-steps{gap:7px}.merchant-store-links{gap:8px}.directory-quote .merchant-x,.card-name .merchant-x{margin-left:0}.directory-quote .merchant-x{max-width:100%}}`;
export function merchantXBadge(offer,profiles=[]){
 const shop=shopDescriptorForOffer(offer),profile=shop&&profiles.find(p=>p.shopId===shop.id);if(!profile)return '';
 return '<a class="merchant-x" href="https://x.com/'+esc(profile.xHandle)+'" target="_blank" rel="noopener noreferrer nofollow ugc" title="店主认领后关联的公开 X 账号；仅核对账号与店铺关联，不代表信誉或交易担保" aria-label="查看店主的 X 账号 @'+esc(profile.xHandle)+'（已关联店铺）"><span class="merchant-x-logo" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.64 7.584H.47l8.6-9.835L0 1.154h7.594l5.243 6.932 6.064-6.933Zm-1.29 19.49h2.039L6.487 3.24H4.3l13.31 17.403Z"/></svg></span><span class="merchant-x-handle">@'+esc(profile.xHandle)+'</span><svg class="merchant-x-check" viewBox="0 0 20 20" aria-hidden="true" focusable="false"><circle cx="10" cy="10" r="9" fill="currentColor"/><path d="m5.8 10 2.7 2.7 5.7-5.5" fill="none" stroke="white" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"/></svg></a>';
}
export function merchantStoreLinks(offer,{showClaim=true}={}){
 const shop=shopDescriptorForOffer(offer);if(!shop)return '';
 return '<div class="merchant-store-links"><a href="'+esc(shopPath(shop.id))+'">店铺主页</a>'+(showClaim?'<a href="/claim-shop?shop='+shop.id+'">我是店主 · 认领 X 账号</a>':'')+'</div>';
}
export function shopContent(shop,profiles=[]){
 const profile=profiles.find(p=>p.shopId===shop.id),share=xShareHref('在 AirRadar 查看这家店铺的 AI 产品报价：'+shop.name,'https://airadar.vip'+shopPath(shop.id));
 const offer={url:shop.url,source:'direct-shops',extra:JSON.stringify({shopUrl:shop.url,shopNo:shop.identity.startsWith('shop:16688:')?shop.identity.split(':').at(-1):undefined})};
 const entries=[...shop.entries].sort((a,b)=>a.productName.localeCompare(b.productName)||String(a.offer.currency).localeCompare(String(b.offer.currency))||a.offer.price-b.offer.price);
 return merchantStyles()+`<section class="merchant" data-shop-id="${esc(shop.id)}"><a href="/">← 返回产品目录</a><header class="intro"><p class="eyebrow">AIRRADAR / 店铺主页</p><h1>${esc(shop.name)}</h1><p>${safeExternalLink(shop.url)}</p><div class="x-public-account">${profile?'<span>店主 X</span>'+merchantXBadge(offer,profiles):'<span class="muted">店主尚未关联 X 账号</span>'}</div><p class="x-note">${profile?'该 X 账号由认领人提交，经人工核对账号控制与店铺关联后展示。':'已收录报价的店铺经营者可以申请关联自己的 X 账号。'}认领不代表商家信用、商品质量或交易安全保证。</p><div class="x-actions"><a class="primary" href="/claim-shop?shop=${shop.id}">${profile?'申请更新 / 更正 X 关联':'我是店主，认领这家店'}</a><a href="${esc(share)}" target="_blank" rel="noopener noreferrer">分享到 X</a></div></header><section class="panel"><h2>这家店的公开报价</h2><p class="muted">${entries.length} 条有效报价，按产品和币种分别列出。以原店结算页面为准。</p>${entries.slice(0,100).map(e=>{
 const href=outboundHref(e.offer,{source:e.list.source,product_id:e.product.product_id}),productHref='/?'+new URLSearchParams({family:e.family,product:e.productKey,spec:e.offer.comparison_key||''});
 return '<article class="x-list-row"><div><h2><a href="'+esc(productHref)+'">'+esc(e.productName)+'</a></h2><p>'+esc(e.offer.comparison_label||'规格待确认')+'</p><p class="muted">'+esc(e.offer.title)+'</p></div><div class="x-list-buy"><strong class="money">'+esc(e.offer.currency)+' '+Number(e.offer.price).toLocaleString('zh-CN')+'</strong>'+(href?'<a class="x-button" data-store-risk data-outbound-target="'+esc(e.offer.url)+'" href="'+esc(href)+'" target="_blank" rel="noopener noreferrer">前往店铺 ↗</a>':'')+'</div></article>';
 }).join('')||'<p>暂时没有可展示的有效报价，店铺与账号关联仍可在本页查看。</p>'}${entries.length>100?'<p class="muted">此页展示前 100 条，可从产品目录查看完整报价。</p>':''}</section></section>`;
}
export function claimContent(csrf,shops,selected=''){
 return merchantStyles()+`<section class="merchant" data-x-claim-page><header class="intro"><p class="eyebrow">FOR SHOP OWNERS / 店主认领</p><h1>让访客知道，店铺背后是你。</h1><p>把自己的 X 账号关联到已收录店铺。审核通过后，访客可从报价页查看你的公开账号，你也可以分享自己的店铺主页。</p><p class="x-steps"><span>① 选择店铺与账号</span><span>② 提交控制证明</span><span>③ 人工审核后展示</span></p></header><input type="hidden" data-x-csrf value="${esc(csrf)}"><div class="message" data-x-message role="status" tabindex="-1" hidden></div>
<form data-x-start><label class="field"><span>查找已收录店铺</span><input data-shop-search type="search" placeholder="输入店铺名或域名筛选" autocomplete="off"></label><label class="field"><span>要认领的店铺</span><select name="shopId" required><option value="">请选择店铺</option>${shops.map(s=>'<option value="'+s.id+'"'+(s.id===selected?' selected':'')+'>'+esc(s.name+' · '+new URL(s.url).hostname+(s.identity.startsWith('shop:')?' · '+new URL(s.url).pathname:''))+'</option>').join('')}</select><small class="muted">找不到店铺？<a href="/submit-shop">先提交收录申请</a>。已有店铺无需重复申请收录。</small></label><label class="field"><span>你的 X 账号</span><input name="xHandle" required maxlength="250" placeholder="@username 或 https://x.com/username" autocomplete="off"><small class="muted">填写你能实际控制的账号，审核通过后公开展示。</small></label><label class="field"><span>联系邮箱</span><input name="email" required type="email" maxlength="254" autocomplete="email"><small class="muted">仅供站长核验联系，不公开。审核进度可凭下一步的专属链接查询。</small></label><label class="check"><input type="checkbox" name="consent" required><span>我有权代表这家店铺，控制所填 X 账号，同意审核后公开展示两者关联，并由站方联系核验。</span></label><div class="trap" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="muted">认领只用于展示账号关联，不影响报价排序，也不是信誉认证。</p><button type="submit">生成认领码</button></form>
<section class="panel" data-x-receipt hidden><h2 data-x-status>准备认领资料</h2><p data-x-summary></p><p class="muted">保存这个进度入口，凭链接可以继续提交或查看结果；请勿公开分享。</p><div class="x-actions"><button type="button" data-x-copy-receipt>复制我的进度链接</button><button type="button" class="secondary" data-x-refresh>刷新审核进度</button></div><p data-x-public-reply></p><div data-x-proof><h3>证明这是你控制的 X 账号</h3><p>在自己的 X 认领帖或个人简介里放入下方认领码和店铺网址，再提交给站长核对。认领码 7 天内有效，不是账号登录验证码。</p><code class="x-claim-code" data-x-code></code><label class="field"><span>可复制的认领内容</span><textarea class="x-proof-text" data-x-proof-text readonly></textarea></label><div class="x-actions"><button type="button" data-x-copy-proof>复制内容</button><a data-x-intent target="_blank" rel="noopener noreferrer">去 X 发布认领帖</a></div><p class="muted">公开发帖由你决定；不想发帖可以暂时把认领码和店铺网址放进 X 简介。本站不会代发帖子。</p>
<form data-x-submit><label class="field"><span>X 控制证明的位置</span><select name="proofType"><option value="post">我发布了认领帖</option><option value="profile">我放到了 X 个人简介</option></select></label><label class="field" data-x-post-field><span>认领帖链接</span><input name="proofUrl" type="url" required maxlength="500" placeholder="https://x.com/username/status/…"></label><label class="field"><span>店铺归属核验链接 <small class="muted">（选填）</small></span><input name="shopProofUrl" type="url" maxlength="500" placeholder="店铺公告或联系页，可展示相同的 X 账号"><small class="muted">独立站请填同域名页面；平台店铺请使用自己的店铺主页。</small></label><label class="field"><span>如何确认你有权代表店铺</span><textarea name="details" required minlength="5" maxlength="1500" placeholder="例如：店铺联系页已放入同一个 X 主页；或说明你能配合的店内公告核验方式。请勿填写密码、API Key 或私密订单资料。"></textarea></label><button type="submit">提交认领审核</button></form></div><div class="x-actions" data-x-published hidden><a class="primary" data-x-shop>查看我的店铺页</a><a data-x-share target="_blank" rel="noopener noreferrer">把店铺页分享到 X</a></div><p><a href="/claim-shop?new=1">申请另一家店铺</a></p></section><noscript><p>提交认领需要 JavaScript；你仍可浏览公开报价，也可以通过页脚联系站长。</p></noscript></section><script src="/assets/merchant-x.js" defer></script>`;
}
export function xClaimsAdminList(service,status='pending'){
 const items=service.list(status),labels={pending:'待审认领',approved:'已展示',rejected:'未通过',revoked:'已撤销'};
 return merchantStyles()+`<div class="merchant"><p>X 关联审核独立于店铺收录与采集。核对账号认领码和店铺归属后，才会在公开报价中展示。</p><nav class="tabs">${Object.entries(labels).map(([key,label])=>'<a href="/admin/x-claims?status='+key+'"'+(key===status?' aria-current="page"':'')+'>'+label+'</a>').join('')}</nav>${items.map(row=>'<article class="panel"><div class="row"><div><h2><a href="/admin/x-claims/'+row.id+'">'+esc(row.shop_name)+'</a></h2><p>'+safeExternalLink(row.shop_url)+'</p><p>X @'+esc(row.x_handle)+'</p></div><span class="badge">'+esc(statuses[row.status])+'</span></div><p class="muted">'+esc(row.created_at)+' · '+esc(row.email)+'</p></article>').join('')||'<section class="panel"><p>暂无此状态的认领。店主提交控制证明后才会进入待审队列。</p></section>'}</div>`;
}
export function xClaimAdminDetail(service,row,csrf){
 const prior=service.profiles().find(p=>p.shopId===row.shop_id),actions=service.actions(row.id);
 return merchantStyles()+`<div class="merchant"><a href="/admin/x-claims">← 返回认领队列</a><section class="panel"><h2>${esc(row.shop_name)} · @${esc(row.x_handle)}</h2><dl><dt>状态</dt><dd>${esc(statuses[row.status])}</dd><dt>店铺</dt><dd>${safeExternalLink(row.shop_url)}</dd><dt>申请人的 X</dt><dd>${safeExternalLink('https://x.com/'+row.x_handle)}</dd><dt>联系邮箱</dt><dd>${esc(row.email)}</dd><dt>认领码</dt><dd><code>${esc(row.code)}</code></dd><dt>X 控制证明</dt><dd>${row.proof_type==='profile'?'X 个人简介':'公开认领帖'} · ${row.proof_url?safeExternalLink(row.proof_url):'尚未提交'}</dd><dt>店铺核验链接</dt><dd>${row.shop_proof_url?safeExternalLink(row.shop_proof_url):'未填写，请按说明人工核对'}</dd><dt>归属说明</dt><dd>${esc(row.details)}</dd><dt>现有 X 关联</dt><dd>${prior?'@'+esc(prior.xHandle):'无'}</dd></dl></section>${['pending','approved'].includes(row.status)?`<form method="post"><h2>核对后处理</h2><input type="hidden" name="csrf" value="${esc(csrf)}"><input type="hidden" name="version" value="${row.version}"><p class="muted">申请人提交的链接只是证据入口，不代表自动验证成功。请检查实际页面，不要仅凭链接文字批准。</p>${row.status==='pending'?'<label class="check"><input type="checkbox" name="xConfirmed" value="true"><span>已打开对应 X 账号，核对认领码与该店铺网址，确认申请人能控制此账号。</span></label><label class="check"><input type="checkbox" name="shopConfirmed" value="true"><span>已通过店铺公告、联系页或独立人工沟通，确认申请人有权代表此店铺。</span></label>':''}${prior&&row.status==='pending'?'<label class="check"><input type="checkbox" name="replaceConfirmed" value="true"><span>已核对已有账号的变更原因，确认用本次认领取代现有 X 关联。</span></label>':''}<label class="field"><span>内部核验依据 / 原因</span><textarea name="note" required minlength="5" maxlength="1500" placeholder="记录实际核验位置与结论；仅站长后台可见"></textarea></label><label class="field"><span>给认领人的说明（选填）</span><textarea name="publicReply" maxlength="1000" placeholder="会出现在认领人的专属进度页，不公开到店铺页"></textarea></label><div class="actions">${row.status==='pending'?'<button name="action" value="approve">通过并展示 X</button><button class="secondary" name="action" value="reject">拒绝本次认领</button>':'<button class="secondary" name="action" value="revoke">撤销 X 关联</button>'}</div></form>`:''}<section class="panel"><h2>审核记录</h2>${actions.map(a=>'<div class="audit"><strong>'+esc({approve:'通过',reject:'拒绝',revoke:'撤销',replace:'替换旧关联'}[a.action])+'</strong><p class="muted">'+esc(a.created_at)+' · '+esc(a.actor)+'</p><p>'+esc(a.note)+'</p></div>').join('')||'<p>尚无审核记录。</p>'}</section></div>`;
}
