import {sponsorEntries,sponsorDirectory,sponsorOfferKey} from './sponsor-service.mjs';
import {sponsorPlan,SPONSOR_PLANS,SPONSOR_THEMES} from './sponsor-plans.mjs';
import {merchantIdForUrl} from './offer-provenance.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localTime=s=>new Date(new Date(s).getTime()+8*3600000).toISOString().slice(0,16);
const status=c=>c.status==='paused'?'已暂停':c.status!=='approved'?'草稿':Date.parse(c.end_at)<=Date.now()?'已到期':Date.parse(c.start_at)>Date.now()?'待开始':'投放中';
export function sponsorAdminContent(db,analytics,url,csrf){
 if(!analytics?.outbound)return '<p>广告统计服务未配置，暂不能建立活动。</p>';
 const all=analytics.outbound.listCampaigns(),id=url.searchParams.get('id'),row=all.find(c=>c.id===id),q=(url.searchParams.get('q')||'').slice(0,100).trim();
 const choices=sponsorEntries(sponsorDirectory(db)).filter(e=>merchantIdForUrl(e.offer.url)),seen=new Set(),filtered=choices.filter(e=>{const key=sponsorOfferKey(e);if(seen.has(key))return false;seen.add(key);return !q||[e.offer.store_name,e.offer.title,e.offer.url].join(' ').toLowerCase().includes(q.toLowerCase())}).slice(0,80);
 const current=row&&choices.find(e=>e.list.source===row.source&&e.product.product_id===row.product_id&&e.offer.offer_id===row.offer_id);if(current&&!filtered.some(e=>sponsorOfferKey(e)===sponsorOfferKey(current)))filtered.unshift(current);
 const token=`<input type="hidden" name="csrf" value="${esc(csrf)}">`,plan=sponsorPlan(row?.placement)||SPONSOR_PLANS[0],now=Date.now()+3600000;
 const reports=analytics.outbound.report(30),metric=id=>reports.filter(r=>r.campaign_id===id).reduce((a,r)=>({clicks:a.clicks+r.clicks,impressions:a.impressions+r.impressions,visible:a.visible+r.visible}),{clicks:0,impressions:0,visible:0});
 return `<style>.sponsor-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sponsor-admin-grid label{display:flex;flex-direction:column;gap:5px;min-width:0}.sponsor-admin-grid input,.sponsor-admin-grid select,.sponsor-admin-grid textarea{max-width:100%;width:100%;box-sizing:border-box}.sponsor-admin-wide{grid-column:1/-1}.sponsor-admin-check{display:flex;gap:10px;margin:16px 0;align-items:flex-start}.sponsor-admin-actions{display:flex;gap:12px;flex-wrap:wrap}.sponsor-admin-table{overflow:auto}.sponsor-admin-table table{min-width:900px;width:100%}.sponsor-admin-table td,.sponsor-admin-table th{padding:10px;text-align:left}.sponsor-admin-table small{display:block}.sponsor-admin-form{margin:20px 0}@media(max-width:760px){.sponsor-admin-grid{grid-template-columns:1fr}}</style>
 <p><a href="/admin/business">商务申请收件箱</a> · <a href="/advertise" target="_blank">前台方案与示例</a> · <a href="/admin/sponsors.csv?days=30">导出近 30 天广告报告</a></p><p>每个页面最多 4 家，共享后置展示。只有审核通过且处于有效档期的活动才展示；不可用报价会自动隐藏。这里不自动收款或发消息。</p>
 <section><h2>${row?'编辑赞助活动':'新建赞助活动'}</h2>${id&&!row?'<p>活动不存在，请重新选择。</p>':''}<form method="get" action="/admin/sponsors"><input type="hidden" name="id" value="${esc(row?.id||'')}"><label>查找已收录报价 <input name="q" maxlength="100" value="${esc(q)}" placeholder="店名、域名或商品名"></label><button>查找</button></form><p>显示最多 80 条候选；共享平台或未核实归属的链接需先完成店铺核验。批准时再次检查最新报价可用性。</p>
 <form class="sponsor-admin-form" method="post" action="/admin/sponsors">${token}<input type="hidden" name="id" value="${esc(row?.id||'')}"><input type="hidden" name="version" value="${row?.version||0}"><div class="sponsor-admin-grid"><label class="sponsor-admin-wide">赞助商对应报价<select name="offer_key" required><option value="">请选择报价</option>${filtered.map(e=>`<option value="${sponsorOfferKey(e)}"${current&&sponsorOfferKey(current)===sponsorOfferKey(e)?' selected':''}>${esc(e.offer.store_name)} · ${esc(e.offer.title)} · ${esc(e.offer.url)}</option>`).join('')}</select></label><label>展示名称<input name="label" required maxlength="80" value="${esc(row?.label||'')}" placeholder="商家名称或简短服务名称"></label><label>投放位置<select name="placement">${SPONSOR_PLANS.map(p=>`<option value="${p.key}"${p.key===plan.key?' selected':''}>${p.label}后置 · 7天参考 ¥${p.prices['7d']}</option>`).join('')}</select></label><label>广告配色<select name="theme">${SPONSOR_THEMES.map(t=>`<option value="${t.key}"${t.key===(row?.theme||'amber')?' selected':''}>${t.label}</option>`).join('')}</select></label><label>广告主标题<input name="headline" maxlength="32" value="${esc(row?.headline||'')}" placeholder="32字内，例如：让灵感，继续发生。"></label><label class="sponsor-admin-wide">广告副标题<input name="tagline" maxlength="48" value="${esc(row?.tagline||'')}" placeholder="48字内，说明一项服务或适用人群；不填写则显示商品标题"></label><p class="sponsor-admin-wide">配色与主视觉采用前台示例的同款模板，可在<a href="/advertise#sponsor-preview" target="_blank">合作页</a>查看。展示名称、主副标题上线前需取得商家确认。</p><p class="sponsor-admin-wide">目标产品或分类由所选报价自动确定，避免投错页面。跨产品、分类和首页需分别建立活动。</p><label>开始时间（北京时间）<input type="datetime-local" name="start_at" value="${localTime(row?.start_at||now)}" required></label><label>结束时间（北京时间）<input type="datetime-local" name="end_at" value="${localTime(row?.end_at||now+7*86400000)}" required></label><label>本次确认金额（元）<input type="number" name="amount_cny" min="0" max="1000000" step="1" value="${row?.amount_cny??plan.prices['7d']}" required></label><p class="sponsor-admin-wide">金额以双方确认为准，修改活动不会自动套用新价。首次试投可从产品页 7 天 ¥${sponsorPlan('product').prices['7d']} 开始。单独约定的优惠需记录在内部备注，续投重新确认；X 推广另行报价。</p><label>内部备注<textarea name="note" maxlength="1000" placeholder="记录申请编号、约定范围、优惠原因与调整说明">${esc(row?.note||'')}</textarea></label></div><label class="sponsor-admin-check"><input type="checkbox" name="reviewed" value="true">我已核对商家、展示内容、费用与档期，确认可以安排该广告</label><div class="sponsor-admin-actions"><button name="action" value="save">保存草稿</button><button name="action" value="approve">批准并按档期展示</button>${row?'<a href="/admin/sponsors">新建其他活动</a>':''}</div></form></section>
 <section><h2>活动与效果（近 30 天）</h2><p>输出、可见展示、点击均按匿名网络/浏览器标识日去重，属于估算；历史可见展示为 0 可能是当时尚未测量，不代表无人看见。无订单回传，不报告销量。</p><div class="sponsor-admin-table"><table><thead><tr><th>活动 / 页面</th><th>状态与档期</th><th>费用</th><th>输出估算</th><th>可见估算</th><th>点击估算</th><th>操作</th></tr></thead><tbody>${all.map(c=>{const m=metric(c.id);return `<tr><td>${esc(c.label)}<small>${esc(sponsorPlan(c.placement)?.label||c.placement)} · ${esc(c.page_label||c.page_key)}</small><small>${esc(c.id)}</small></td><td>${status(c)}<small>${localTime(c.start_at).replace('T',' ')} 至 ${localTime(c.end_at).replace('T',' ')}</small></td><td>¥${c.amount_cny}</td><td>${m.impressions}</td><td>${m.visible}</td><td>${m.clicks}</td><td><a href="/admin/sponsors?id=${encodeURIComponent(c.id)}">编辑</a>${c.status==='approved'?`<form method="post" action="/admin/sponsors">${token}<input type="hidden" name="id" value="${esc(c.id)}"><input type="hidden" name="version" value="${c.version}"><button name="action" value="pause">暂停</button></form>`:''}</td></tr>`}).join('')}</tbody></table></div>${all.length?'':'<p>尚无广告活动。展示示例不会产生正式活动。</p>'}</section>${row?`<section><h2>该活动操作记录</h2>${analytics.outbound.actions(row.id).map(a=>`<p>${esc(localTime(a.created_at))} · ${esc(a.actor)} · ${esc(a.action)} · 版本 ${a.version}</p>`).join('')||'<p>旧活动暂无操作记录</p>'}</section>`:''}`;
}
export function exportSponsors(res,analytics,days=30){
 if(!analytics?.outbound){res.statusCode=503;res.end('广告统计服务未配置');return;}
 days=Number(days)===7?7:30;const reports=analytics.outbound.report(days).filter(r=>r.campaign_id),campaigns=new Map(analytics.outbound.listCampaigns().map(c=>[c.id,c]));
 const rows=[...campaigns.values()].map(c=>reports.filter(r=>r.campaign_id===c.id).reduce((a,r)=>({...a,impressions:a.impressions+r.impressions,visible:a.visible+r.visible,clicks:a.clicks+r.clicks}),{campaign_id:c.id,placement:c.placement,impressions:0,visible:0,clicks:0}));
 const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
 const body=[['统计窗口（天）','活动','赞助商','位置','页面','输出访客估算（日去重）','可见访客估算（日去重）','出站点击估算（日去重）','本次确认总金额（非该窗口分摊）','订单数据'],...rows.map(r=>{const c=campaigns.get(r.campaign_id);return [days,r.campaign_id,c?.label,sponsorPlan(r.placement)?.label,c?.page_label,r.impressions,r.visible,r.clicks,c?.amount_cny,'未回传，不估算']})].map(row=>row.map(cell).join(',')).join('\r\n');
 res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="airadar-sponsors.csv"');res.end('\ufeff'+body);
}
