import {SPONSOR_PLANS,SPONSOR_THEMES,sponsorPlan} from './sponsor-plans.mjs';
import {quoteTimeInfo} from './offer-provenance.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function sponsorBlock(items,{demo=false,placement='product'}={}){
 if(!items.length)return '';
 const plan=sponsorPlan(placement)||SPONSOR_PLANS[0],cards=items.slice(0,4);
 const rendered=cards.map(({campaign:c,offer:o,href,viewToken})=>{
  const time=quoteTimeInfo(o),price=o.price!=null?`${o.currency==='CNY'?'¥':esc(o.currency)+' '}${Number(o.price).toLocaleString('zh-CN')}`:'价格以商家为准';
  const theme=SPONSOR_THEMES.some(t=>t.key===c.theme)?c.theme:'amber';
  const headline=c.headline||c.label||o.store_name,tagline=c.tagline||o.title;
  const action=demo?'<button type="button" class="offer-shop-button" data-sponsor-demo>了解店铺 ↗</button>':`<a class="offer-shop-button" data-store-risk data-outbound-target="${esc(o.url)}" href="${esc(href)}" target="_blank" rel="noopener noreferrer nofollow sponsored">了解店铺 ↗</a>`;
  return `<article class="sponsor-card" data-sponsor-theme="${theme}"${!demo&&viewToken?` data-sponsor-id="${esc(c.id)}" data-sponsor-token="${esc(viewToken)}"`:''}>
   <div class="sponsor-creative"><img src="/assets/sponsor-${theme}.webp" width="768" height="512" alt="" loading="lazy" decoding="async"><div class="sponsor-creative-copy"><span class="sponsor-brand">${esc(c.label||o.store_name)}</span><strong>${esc(headline)}</strong><span class="sponsor-tagline">${esc(tagline)}</span></div></div>
   <div class="sponsor-card-body"><div class="sponsor-card-copy"><h3>${esc(c.label||o.store_name)}</h3><p>${esc(o.title)}</p><p class="sponsor-quote"><strong class="money">${price}</strong> · 在售</p><span class="quote-provenance">报价时间 · <time${time.absolute?` datetime="${esc(time.absolute)}"`:''}>${esc(time.relative)}</time></span></div>${action}</div>
  </article>`;
 }).join('');
 return `<section class="surface sponsored-area sponsor-strip" data-sponsor-count="${cards.length}" aria-label="${demo?'虚构赞助示例':'Sponsored 广告'}"><div class="sponsor-heading"><h2>支持本站的赞助商</h2><span>Sponsored / 广告${demo?' · 虚构示例':''}</span></div><div class="sponsor-grid">${rendered}</div><div class="sponsor-foot"><span>广告独立展示，不影响自然排序。${sponsorFit}</span>${demo?'':`<a href="/advertise?placement=${plan.key}">我也想赞助 ↗</a>`}</div></section>`;
}
const sponsorFit='适合云服务器、IP 服务、网络检测、域名与开发者工具等商家。';
export function sponsorInvite(placement){return `<aside class="sponsor-invite" aria-label="赞助合作"><div><strong>让你的服务，被需要的人看见。</strong><p>${sponsorFit}在读者浏览完主要内容后，用一张简洁的图文卡片介绍你的服务。</p></div><div class="sponsor-invite-actions"><a href="/advertise?placement=${esc(placement)}">查看展示示例 ↗</a><a href="https://t.me/lincwang" target="_blank" rel="noopener noreferrer">TG 咨询合作 ↗</a></div></aside>`;}
const mockItems=count=>Array.from({length:count},(_,i)=>({campaign:{label:'示例店铺 '+String.fromCharCode(65+i),theme:SPONSOR_THEMES[i].key,headline:['让灵感，继续发生。','把时间留给好想法。','下一次续费，多个选择。','你的 AI 日常，从这里续上。'][i],tagline:['订阅服务 · 先了解，再选择','日常创作，多一种可能','清楚的规格，适合自己的方案','选好服务，再出发'][i]},offer:{title:['ChatGPT Plus 代充 · 1个月','Claude Pro 代充 · 1个月','Gemini Pro 订阅 · 1个月','AI 订阅服务 · 规格详见商家'][i],price:[99,109,119,129][i],currency:'CNY',last_verified_at:new Date().toISOString()}}));
export function sponsorAdvertiseContent(url=new URL('https://airadar.vip/advertise')){
 const plan=sponsorPlan(url.searchParams.get('placement'))||SPONSOR_PLANS[0],count=[1,2,3,4].includes(Number(url.searchParams.get('count')))?Number(url.searchParams.get('count')):1;
 const href=(key,n)=>`/advertise?placement=${key}&count=${n}#sponsor-preview`,apply=(key,d)=>`/submit?topic=sponsor_apply&placement=${key}&duration=${d}`;
 const items=mockItems(count);if(plan.key==='product')items.forEach(i=>i.offer.title='ChatGPT Plus 代充 · 1个月');if(plan.key==='category')items.forEach((i,n)=>i.offer.title=['ChatGPT Plus 代充 · 1个月','ChatGPT Pro 服务 · 规格详见商家'][n%2]);
 const context=plan.key==='product'?'<h3>ChatGPT Plus · 店铺报价</h3><div class="sponsor-demo-row"><span>正常报价示例 A</span><strong>¥89</strong></div><div class="sponsor-demo-row"><span>正常报价示例 B</span><strong>¥99</strong></div><p class="note">当页报价列表与分页结束</p>':plan.key==='category'?'<h3>ChatGPT · 产品分类</h3><div class="sponsor-demo-row"><span>ChatGPT Plus</span><span>查看店铺 →</span></div><div class="sponsor-demo-row"><span>ChatGPT Pro</span><span>查看店铺 →</span></div><p class="note">该分类的产品列表结束</p>':'<h3>AI 订阅报价 · 首页</h3><div class="sponsor-demo-row"><span>ChatGPT / Claude / Gemini</span><span>产品导航</span></div><div class="sponsor-demo-row"><span>其他产品分类</span><span>浏览分类 →</span></div><p class="note">首页分类与产品导航结束</p>';
 return `<section class="sponsor-intro"><p class="commerce-eyebrow">AIradar · 商家合作</p><h1>让比较价格的人，<br>多了解你的店铺。</h1><p>支持 7、14、28 天合作档期。首页、分类页、产品页均采用后置展示，同页最多 4 家，共享位置。</p><a class="offer-shop-button" href="${apply(plan.key,'7d')}">获取${plan.label}合作报价</a></section>
 <section id="sponsor-preview" class="sponsor-preview"><h2>先看位置，再选方案</h2><p class="note">下方商家与报价均为虚构示例，不代表本站已获赞助。页面内容做了缩略，广告始终位于实际列表之后。</p><nav class="sponsor-selector" aria-label="示例页面">${SPONSOR_PLANS.map(p=>`<a href="${href(p.key,count)}" aria-current="${p.key===plan.key?'true':'false'}">${p.label}</a>`).join('')}</nav><nav class="sponsor-selector" aria-label="示例赞助商数量">${[1,2,3,4].map(n=>`<a href="${href(plan.key,n)}" aria-current="${n===count?'true':'false'}">${n} 家赞助商</a>`).join('')}</nav><div class="sponsor-demo-context" data-preview-page="${plan.key}">${context}${sponsorBlock(items,{demo:true,placement:plan.key})}<p class="note">${plan.key==='product'?'购买参考与页尾内容':'页尾内容'}</p></div><p id="sponsor-demo-status" role="status" class="note"></p></section>
 ${sponsorGuidance()}
 <section class="sponsor-rates"><h2>选择页面与档期</h2><p class="note">付费赞助，合作费用与档期人工确认。同一页面最多 4 家，不承诺独占或固定展示顺序。</p><div class="table-scroll"><table><thead><tr><th>投放页面</th><th>7 天</th><th>14 天</th><th>28 天</th></tr></thead><tbody>${SPONSOR_PLANS.map(p=>`<tr><th scope="row">${p.label}<small>${p.description}</small></th>${['7d','14d','28d'].map(d=>`<td><a href="https://t.me/lincwang" target="_blank" rel="noopener noreferrer" aria-label="在 Telegram 咨询${p.label}${parseInt(d)}天赞助">获取报价</a></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="note">产品页对应一个产品，分类页只对应一个分类列表，不包含该分类下的产品详情页；首页只对应首页。点击“获取报价”将在 Telegram 联系 @lincwang，请注明投放页面与档期。</p></section>
 <section class="sponsor-terms"><h2>你会得到什么</h2><ul><li>一个明确页面中的赞助展示、电脑和手机适配。</li><li>素材排版及投放期内两次小幅文案调整。</li><li>结束后的该活动展示与出站点击报告；有商家订单回传时再核对成交。</li></ul><h2>合作怎么开始</h2><ol><li>选择位置与档期，提交店铺和联系方式。</li><li>人工核对店铺、内容、可用档期及费用。</li><li>双方确认后安排上线，从正常展示开始计时。</li></ol><p>示例和申请不代表已购买，也不锁定名额。合作费用由双方确认，已确认订单按原约定执行，到期不自动续费。</p><details><summary>展示、退款和合作边界</summary><p>同一页面最多 4 家，付费不改变自然报价排名，也不代表交易安全保证。不含站长 X 推文，X 推广另行沟通；不承诺最低曝光、点击或成交。</p><p>上线前取消可退还广告费。网站原因无法展示，等时补足或按不可用时长比例退款；提前结束按套餐价退还未执行时长。具体起止时间、费用和处理方式由双方确认。</p><p>输出展示与可见展示分开记录：可见展示需在前台页面中至少 50% 面积持续进入屏幕 1 秒，统计按匿名网络/浏览器标识日去重，是估算，不等于独立自然人数。页面末尾的广告需要滚动才可能看见。未回传订单时不编造成交数据。</p></details><p class="note">合作费用与档期人工确认，申请内容仅供后台处理。</p></section><section class="sponsor-starter sponsor-fit"><h2>你的服务，也可以出现在这里。</h2><p>${sponsorFit}首页底部适合介绍品牌与服务；分类页、产品页则根据读者需求匹配，广告均在主要内容之后展示。</p><p>准备品牌名称、一句话介绍和落地页链接，通过 TG 沟通投放页面、素材与档期。费用单独沟通，确认后安排上线。</p><a href="https://t.me/lincwang" target="_blank" rel="noopener noreferrer">联系 @lincwang 咨询合作 ↗</a></section>`;
}
function sponsorGuidance(){
 const apply=key=>`/submit?topic=sponsor_apply&placement=${key}&duration=7d`;
 const guidance=[
  {key:'product',name:'产品页 · 把一项服务讲清楚',intro:'面向已经选定产品、正在比较商家的读者。',fit:'主营某一款订阅，或想先测试一个优势商品的店铺。',material:'突出具体产品、周期和交付方式；用一句话说明服务特点。',advice:'第一次投放可以从这里开始：选主营产品，试投 7 天，先观察该广告的可见展示与出站点击。'},
  {key:'category',name:'分类页 · 展示同类服务',intro:'面向浏览同一产品家族、还在选择具体方案的读者。',fit:'同一分类下有多个产品，想让读者记住店名的商家。',material:'以店铺名称为主，说明覆盖的产品和服务范围，避免堆满价格。',advice:'适合已经有清楚的服务介绍页的商家。分类页投放只覆盖分类列表，产品详情需单独安排。'},
  {key:'home',name:'首页 · 先认识你的服务',intro:'面向从首页浏览不同产品分类的读者。',fit:'云服务器、IP 服务、网络检测、域名、开发者工具，以及经营多个品类的商家。',material:'使用辨识度高的配色，一句核心介绍，加一个清楚的进入店铺按钮。',advice:'首页不一定点击更多。只有读者滚动到导航内容后，才可能看到广告；建议结合实际报告判断是否续投。'}
 ];
 return `<section class="sponsor-guidance"><div class="sponsor-guidance-heading"><h2>选对位置，比一开始投得多更重要。</h2><p>下面是按页面浏览场景给出的投放建议，效果需要用你的活动数据验证。</p></div><div class="sponsor-guidance-list">${guidance.map(g=>`<article class="sponsor-guidance-card"><div><h3>${g.name}</h3><p class="sponsor-guidance-intro">${g.intro}</p></div><dl><dt>适合谁</dt><dd>${g.fit}</dd><dt>素材怎么做</dt><dd>${g.material}</dd></dl><p class="sponsor-guidance-advice">${g.advice}</p><a href="${apply(g.key)}">咨询${sponsorPlan(g.key).label}合作 ↗</a></article>`).join('')}</div><div class="sponsor-starter"><h3>第一次合作，先跑完一个小周期。</h3><p>优先选主营产品页，准备店名、一句主张、服务说明和店铺链接。我们确认素材与档期后上线，期末核对可见展示和出站点击，再决定续投或调整位置。</p><p>你的广告可以有自己的色彩。四套配色与主视觉均可用于正式投放，主标题和副标题由商家确认；本站页面保持原有风格。</p></div></section>`;
}
export const SPONSOR_CSS=`
.sponsor-invite{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:20px 0;margin:24px 0 0;border-top:1px solid #d7e1db;color:#52645c;font-size:13px;line-height:1.8}.sponsor-invite strong{font-size:15px;color:#294736}.sponsor-invite p{margin:5px 0 0;max-width:710px}.sponsor-invite-actions{display:flex;flex:0 0 auto;gap:14px;flex-wrap:wrap}.sponsor-invite a,.sponsor-fit>a{color:#216d57;text-decoration:underline;text-underline-offset:4px}.sponsor-fit{box-sizing:border-box}.sponsor-fit h2{font-size:20px}.sponsor-foot>span{line-height:1.7}
@media(max-width:600px){.sponsor-invite{align-items:flex-start;flex-direction:column;gap:12px}.sponsor-invite-actions{gap:18px}}

.sponsor-intro,.sponsor-preview,.sponsor-guidance,.sponsor-rates,.sponsor-terms,.sponsor-fit{max-width:1000px;margin:0 auto 42px}
.sponsor-intro{padding:16px 0 10px}.sponsor-intro h1{font-size:38px;line-height:1.35;letter-spacing:-.04em;margin:12px 0 18px}.sponsor-intro>p:not(.commerce-eyebrow){color:#52645c;max-width:670px;line-height:1.8}.sponsor-intro>.offer-shop-button{margin-top:12px;background:#216d57;color:#fff;border-color:#216d57}
.sponsor-preview{scroll-margin-top:190px}.sponsor-preview>h2,.sponsor-rates>h2,.sponsor-guidance-heading h2,.sponsor-terms>h2{font-size:24px;line-height:1.45;margin:0 0 12px;letter-spacing:-.02em}
.sponsor-selector{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.sponsor-selector a{padding:9px 14px;border:1px solid #d5dfda;border-radius:6px;color:#42574b;background:#fff;font-size:13px}.sponsor-selector a[aria-current=true]{background:#e9f3ed;border-color:#216d57;color:#19563f}.sponsor-selector a:focus-visible,.sponsor-card a:focus-visible,.sponsor-card button:focus-visible{outline:3px solid #216d57;outline-offset:3px}
.sponsor-demo-context{border:1px solid #d4e1d8;border-radius:10px;padding:22px;background:#f8faf9}.sponsor-demo-context>h3{font-size:17px;margin:0 0 14px}.sponsor-demo-row{padding:11px 0;border-bottom:1px solid #e1e8e3;display:flex;justify-content:space-between;gap:16px;font-size:13px;color:#52645c}.sponsor-demo-context>.note{margin:12px 0;color:#526559}
.sponsor-strip{margin:24px 0;padding:20px;border:1px solid #d7e1db;border-radius:9px;background:#fff}.sponsor-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.sponsor-heading h2{font-size:16px;line-height:1.4;margin:0;color:#294736}.sponsor-heading>span{font-size:11px;color:#56655e;white-space:nowrap}
.sponsor-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sponsor-strip[data-sponsor-count="1"] .sponsor-grid{grid-template-columns:minmax(0,1fr)}.sponsor-strip[data-sponsor-count="3"] .sponsor-grid{grid-template-columns:repeat(3,minmax(0,1fr))}
.sponsor-strip .sponsor-card{--ad-ink:#853607;--ad-accent:#d3570a;--ad-light:#fff2df;min-width:0;display:flex;flex-direction:column;padding:0;overflow:hidden;border:1px solid #e0e5e1;border-radius:8px;background:#fff}
.sponsor-strip [data-sponsor-theme="blue"]{--ad-ink:#143b87;--ad-accent:#205dce;--ad-light:#eaf3ff}.sponsor-strip [data-sponsor-theme="violet"]{--ad-ink:#5a2879;--ad-accent:#8543ab;--ad-light:#f5edfb}.sponsor-strip [data-sponsor-theme="green"]{--ad-ink:#12593d;--ad-accent:#137953;--ad-light:#e5f6ee}
.sponsor-creative{position:relative;isolation:isolate;background:var(--ad-light);min-height:186px;overflow:hidden;flex-shrink:0}.sponsor-creative>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:-2}.sponsor-creative::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,var(--ad-light) 0%,transparent 90%);z-index:-1}.sponsor-creative-copy{position:relative;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;width:74%;min-height:186px;height:100%;padding:19px;box-sizing:border-box;color:var(--ad-ink)}.sponsor-brand{overflow-wrap:anywhere;font-size:10px;line-height:1.5;letter-spacing:.04em;margin-bottom:10px}.sponsor-creative-copy>strong{font-size:23px;font-weight:750;line-height:1.35;letter-spacing:-.03em;overflow-wrap:anywhere;text-wrap:balance}.sponsor-tagline{font-size:10px;line-height:1.5;margin-top:11px;max-width:190px;overflow-wrap:anywhere}
.sponsor-card-body{display:flex;flex:1;flex-wrap:wrap;justify-content:space-between;align-items:flex-end;gap:12px;padding:17px}.sponsor-card-copy{flex:1 1 145px;min-width:0}.sponsor-strip .sponsor-card h3{font-size:15px;margin:0 0 7px;overflow-wrap:anywhere;line-height:1.5}.sponsor-strip .sponsor-card p{font-size:12px;line-height:1.6;margin:5px 0;color:#526259;overflow-wrap:anywhere}.sponsor-strip .sponsor-card .money{font-size:17px}.sponsor-strip .sponsor-card .quote-provenance{font-size:10px;color:#53665a}.sponsor-strip .sponsor-card .offer-shop-button{min-height:40px;font-family:inherit;font-weight:600;font-size:12px;line-height:1.4;white-space:nowrap;margin:0;padding:10px 13px;cursor:pointer;background:var(--ad-accent);color:#fff;border:0;border-radius:5px}.sponsor-strip .sponsor-card .offer-shop-button:hover{filter:brightness(.9)}
.sponsor-strip[data-sponsor-count="1"] .sponsor-card{display:grid;grid-template-columns:1.12fr 1fr}.sponsor-strip[data-sponsor-count="1"] .sponsor-creative,.sponsor-strip[data-sponsor-count="1"] .sponsor-creative-copy{min-height:210px}.sponsor-strip[data-sponsor-count="1"] .sponsor-card-body{padding:24px}.sponsor-strip[data-sponsor-count="1"] .sponsor-creative-copy>strong{font-size:27px}.sponsor-strip[data-sponsor-count="3"] .sponsor-creative-copy{width:86%;padding:16px}.sponsor-strip[data-sponsor-count="3"] .sponsor-creative-copy>strong{font-size:21px}.sponsor-strip[data-sponsor-count="3"] .sponsor-card-body{padding:15px}
.sponsor-foot{display:flex;justify-content:space-between;gap:10px;margin-top:14px;font-size:11px;color:#59685f}.sponsor-foot a,.sponsor-invite a{color:#245e41;text-decoration:underline;text-underline-offset:3px}
.sponsor-guidance-heading{margin-bottom:22px}.sponsor-guidance-heading p{font-size:14px;line-height:1.8;color:#52645c}.sponsor-guidance-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.sponsor-guidance-card{background:#f4f7f5;border-radius:9px;padding:25px;display:flex;flex-direction:column;align-items:flex-start}.sponsor-guidance-card:last-child{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;gap:0 32px}.sponsor-guidance-card h3{font-size:19px;line-height:1.5;margin:0 0 9px;letter-spacing:-.02em}.sponsor-guidance-card p,.sponsor-guidance-card dd{font-size:14px;line-height:1.85;color:#52645c;margin:0}.sponsor-guidance-card dl{margin:16px 0}.sponsor-guidance-card dt{font-size:13px;font-weight:650;color:#216d57;margin:0 0 7px}.sponsor-guidance-card dd+dt{margin-top:18px}.sponsor-guidance-card .sponsor-guidance-advice{border-top:1px solid #dce5df;padding-top:16px;font-size:13px;margin-top:auto}.sponsor-guidance-card>a{font-size:13px;font-weight:600;color:#216d57;padding-top:18px}.sponsor-guidance-card:last-child dl{grid-column:2;grid-row:1/3;margin:0}.sponsor-guidance-card:last-child .sponsor-guidance-advice{grid-column:1;margin-top:18px}.sponsor-starter{padding:24px 0 0;max-width:740px}.sponsor-starter h3{font-size:17px;margin:0 0 10px}.sponsor-starter p{color:#52645c;font-size:14px;line-height:1.9}
.sponsor-rates table{width:100%;border-collapse:collapse;background:#fff}.sponsor-rates th,.sponsor-rates td{text-align:left;padding:17px 14px;border-bottom:1px solid #dce4df}.sponsor-rates th{font-size:14px}.sponsor-rates th small{display:block;font-size:11px;font-weight:400;color:#586d60;margin-top:5px}.sponsor-rates td a{font-size:16px;font-weight:700;color:#216d57;text-decoration:underline;text-underline-offset:5px;white-space:nowrap}.sponsor-terms{line-height:1.8;color:#465c4d}.sponsor-terms li{margin:7px 0}.sponsor-terms h2{color:#243b2c;margin-top:22px}.sponsor-terms details{padding:14px 0;border-top:1px solid #d4dfd8}.sponsor-terms summary{cursor:pointer;font-weight:600}.sponsor-application-note{padding:14px;background:#edf5ef;border:1px solid #c9ddce;border-radius:7px;line-height:1.7}
@media(max-width:760px){
 .sponsor-preview{scroll-margin-top:270px}.sponsor-intro h1{font-size:29px}.sponsor-preview>h2,.sponsor-rates>h2,.sponsor-guidance-heading h2,.sponsor-terms>h2{font-size:21px}.sponsor-demo-context{padding:13px}.sponsor-selector{gap:6px}.sponsor-selector a{padding:9px 10px;font-size:12px}.sponsor-strip{padding:12px;margin:17px 0 21px}.sponsor-heading{align-items:flex-start;gap:8px}.sponsor-heading h2{font-size:14px}.sponsor-heading>span{font-size:10px;white-space:normal;text-align:right}.sponsor-grid,.sponsor-strip[data-sponsor-count="3"] .sponsor-grid{grid-template-columns:minmax(0,1fr);gap:13px}.sponsor-strip[data-sponsor-count="1"] .sponsor-card{display:flex;flex-direction:column}.sponsor-creative,.sponsor-strip[data-sponsor-count="1"] .sponsor-creative,.sponsor-creative-copy,.sponsor-strip[data-sponsor-count="1"] .sponsor-creative-copy{min-height:150px}.sponsor-creative-copy,.sponsor-strip[data-sponsor-count="3"] .sponsor-creative-copy{width:76%;padding:16px}.sponsor-creative-copy>strong,.sponsor-strip[data-sponsor-count="1"] .sponsor-creative-copy>strong,.sponsor-strip[data-sponsor-count="3"] .sponsor-creative-copy>strong{font-size:23px}.sponsor-brand{font-size:9px;margin-bottom:8px}.sponsor-tagline{font-size:9px;margin-top:9px}.sponsor-card-body,.sponsor-strip[data-sponsor-count="1"] .sponsor-card-body,.sponsor-strip[data-sponsor-count="3"] .sponsor-card-body{padding:13px;gap:8px}.sponsor-card-copy{flex-basis:125px}.sponsor-strip .sponsor-card h3{font-size:13px}.sponsor-strip .sponsor-card p{font-size:11px}.sponsor-strip .sponsor-card .offer-shop-button{font-size:11px;padding:9px;min-height:42px}.sponsor-strip .sponsor-card .quote-provenance{font-size:9px}.sponsor-foot{font-size:10px;flex-wrap:wrap}
 .sponsor-guidance-list{grid-template-columns:minmax(0,1fr)}.sponsor-guidance-card,.sponsor-guidance-card:last-child{display:flex;padding:21px}.sponsor-guidance-card:last-child dl{margin:16px 0}.sponsor-guidance-card:last-child .sponsor-guidance-advice{margin-top:0}.sponsor-guidance-card h3{font-size:18px}.sponsor-guidance-card p,.sponsor-guidance-card dd{font-size:13px}.sponsor-rates th,.sponsor-rates td{padding:12px 8px}.sponsor-rates td a{font-size:13px}.sponsor-rates th{font-size:12px}.sponsor-rates th small{font-size:10px}.sponsor-rates .table-scroll{overflow-x:auto}.sponsor-rates table{min-width:330px}.sponsor-terms{font-size:14px}
}
`;
